// import type { Metadata } from "next";
// import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";

// const plusJakarta = Plus_Jakarta_Sans({
//   variable: "--font-plus-jakarta",
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Veloo Service Provider Dashboard",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={plusJakarta.variable}>
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }

import type React from "react";
import { Header } from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import "../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Metadata } from "next";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Veloo Service Provider Dashboard",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="antialiased">
        <div className="flex min-h-screen gap-8 bg-[#ECFDF5]">
          {/* Sidebar */}
          <Sidebar />

          <div className="flex flex-1 flex-col">
            {/* Header */}
            <Header title="Dashboard" subtitle="Welcome back, Sharon" />

            {/* Main Content */}
            <main className="flex-1 p-6 ">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
